data=trees
library(ggplot2)
View(trees)
count = table(trees$Girth,trees$Height)
count1 = table(trees$Girth,trees$Volume)
count2 = table(trees$Height,trees$Girth)
count3 = table(trees$Height,trees$Volume)
count4 = table(trees$Volume,trees$Girth)
count5 = table(trees$Volume,trees$Height)
barplot(count,main = "GIRTH VS HEIGHT BARPLOT",xlab = "GIRTH",ylab = "HEIGHT",col = c("red","yellow"))
barplot(count1,main = "GIRTH VS VOLUME",xlab = "GIRTH",ylab = "VOLUME",col = c("orange","red"))
barplot(count,main = "HEIGHT VS GIRTH BARPLOT",xlab = "HEIGHT",ylab = "GIRTH",col = c("blue","pink"))
barplot(count,main = "HEIGHT VS VOLUME BARPLOT",xlab = "HEIGHT",ylab = "VOLUME",col = c("brown","green"))
barplot(count,main = "VOLUME VS GIRTH BARPLOT",xlab = "VOLUME",ylab = "GIRTH",col = c("lightblue","purple"))
barplot(count,main = "VOLUME VS HEIGHT BARPLOT",xlab = "VOLUME",ylab = "HEIGHT",col = c("azure","maroon"))
hist(trees$Girth,breaks = 10,col = "red")
hist(trees$Height,breaks = 10,col = "cyan")
hist(trees$Volume,breaks = 10,col = "brown")

library(plotrix)
plot(trees)
plot(trees$Girth,main = "LINE CHART FOR GIRTH OF TREES",type = "b",col = "darkblue")
plot(trees$Height,main = "LINE CHART FOR HEIGHT OF TREES",type = "b",col = "red")
plot(trees$Volume,main = "LINE CHART FOR VOLUME OF TREES",type = "b",col = "orange")

boxplot(trees$Girth,main = "GIRTH OF TREES",varwidth = TRUE,col = "red")
boxplot(trees$Height,main ="HEIGHT OF TREES",varwidth = TRUE,col = "purple")
boxplot(trees$Volume,main = "VOLUME OF TREES",varwidth = TRUE,col = "cyan")

density_data = density(trees$Girth)
density_data2 = density(trees$Height)
density_data3 = density(trees$Volume)
plot(density_data)
plot(density_data2)
plot(density_data3)
polygon(density_data,col = "yellow",border = "black")
polygon(density_data2,col = "green",border = "black")
polygon(density_data3,col = "purple",border = "black")

pie(trees$Girth,main = "GIRTH OF A TREES",col = rainbow(31))
pie(trees$Height,main = "HEIGHT OF TREES",col = rainbow(31))
pie(trees$Volume,main = "VOLUME OF TREES",col = rainbow(31))
pie3D(trees$Girth,main = "GIRTH OF A TREES",col = rainbow(31))
pie3D(trees$Height,main = "HEIGHT OF TREES",col = rainbow(31))
pie3D(trees$Volume,main = "VOLUME OF TREES",col = rainbow(31))
pie3D(trees$Girth,main = "GIRTH OF A TREES",col = rainbow(31),explode = 1.0)
pie3D(trees$Height,main = "HEIGHT OF TREES",col = rainbow(31),explode = 1.0)
pie3D(trees$Volume,main = "VOLUME OF TREES",col = rainbow(31),explode = 1.0)


